### ISSUE TITLE
Availability of original C implementation

### ISSUE THREAD

**Issue by enpinion** [gopro/cineform-sdk#41]
Hi, I'd like to ask if there are still any original C implementation codes available.

I'm currently working on multi-platform codes and revive cross-platform implementation of `_PROCESSOR_DISPATCH` feature for SIMD like SSE2, AVX2 and AVX-512 implementations for the future while keep the backwards compatibility.
And it seems some functions only have SSE2/MMX codes with no corresponding C implementation left. Maybe I could rewrite them in C but before doing this, I'd like to ask if they are available.

Regards.

**Comment by dnewman-gpsw** [comment]
Unfortunately many of these procedures where written directly in SSE2, with no C equivalent.

**Comment by dnewman-gpsw** [comment]
Pleased to hear you are considering AVX2 and AVX-512.

**Comment by enpinion** [comment]
Thank you for the reply.
