### ISSUE TITLE
Building on Debian Jessie

### ISSUE THREAD

**Issue by jonmatifa** [gopro/cineform-sdk#5]
I was able to successfully build this project on Debian Jessie with a couple of notes.

First, it is necessary to install cmake through jessie-backports to ensure you are on 3.5.1+

Second, I had to edit Example/TestCFHD.cpp line 497 from:

`else sprintf_s(restxt, sizeof(restxt), "THUM");`

to:

`else sprintf(restxt, "THUM");`

as "sprintf_s" is apparently not a standard c/c++ function, but sprintf will work with a change in parameters.

**Comment by dnewman-gpsw** [comment]
Thank you for the report of the successful Debian Jessie port. I fixed the sprintf() issue.  I don't know how old the CMake version can be.  I was on v3.8, another developer reported 3.5.1 worked fine, maybe even older works.
